# Generated by Django 5.0.6 on 2024-08-07 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
