# Generated by Django 5.0.6 on 2024-08-08 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0003_rename_create_by_category_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ('-created_at',)},
        ),
    ]
